# Generated by Django 6.0.1 on 2026-04-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingentry',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='readingentry',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('reading', 'Reading'), ('finished', 'Finished'), ('dropped', 'Dropped')], default='planned', max_length=20),
        ),
    ]
