# Generated by Django 6.0.1 on 2026-04-19 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_book_cover_image_book_description_and_more'),
        ('tracker', '0002_readingentry_rating_alter_readingentry_status'),
    ]

    operations = [
    ]
