# Generated by Django 6.0.4 on 2026-04-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='read_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=200),
        ),
    ]
