# Generated by Django 6.0.4 on 2026-04-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_book_read_link_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingentry',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
